spring:
  application:
    name: realtime-server

  data:
    redis:
      host: ${REDIS_DB}
      port: ${REDIS_PORT}
kis:
  key:
    socketKey: ${KIS_SOCKET_KEY}

kafka:
  bootstrap-server: ${KAFKA_SERVER}

server:
  port: 9000